name: Continuous integration

on:
  push:
    branches-ignore: deploy/gh-pages

jobs:
  build:
    name: Build the website
    uses: ./.github/workflows/build.yaml
    with:
      baseurl: /

  lighthouse:
    # A tool to measure website performance. See also:
    # - https://github.com/GoogleChrome/lighthouse
    # - https://github.com/GoogleChrome/lighthouse-ci
    # - https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md

    needs: [build]
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Download build artifact for CI
        uses: actions/download-artifact@v4
        with:
          name: "build"
          path: "src/_site/"

      - name: Install NPM packages
        run: |
          npm ci

      - name: Run lighthouse
        run: |
          npm run lighthouse

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci

          # we need this because the folders/files start with a `.` which is considered to be hidden on Linux
          include-hidden-files: true
